 #include "stdafx.h"

#ifndef TESTSUITE_IDTESTS_H
#define TESTSUITE_IDTESTS_H

#define TESTID_PHASE1_PLAYBACKLOAD 1001
#define TESTID_PHASE1_PLAYBACKLOAD_LINKED 1002
#define TESTID_PHASE1_PLAYBACKINTRO_ALPHA 1003

#endif